name: Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 6

    strategy:
      matrix:
        node_version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest] #, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.0

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            dist
            coverage

  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Code Test and Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 8b43f0ce3ac2b1765a89064593546e7c0a971169e75d8f64a94f405e7e317e17
        with:
#          coverageCommand: yarn run test
          coverageLocations: ${{github.workspace}}/coverage/clover.xml:clover
